from __future__ import annotations

import html
import json
import re
from pathlib import Path

from changeguard.files import write_json
from changeguard.models import AnalysisResult, DatasetContext, DatasetSchema, Severity


def _relation_from_urn(urn: str) -> str:
    match = re.fullmatch(r"urn:li:dataset:\(urn:li:dataPlatform:[^,]+,(.*),[^,]+\)", urn)
    return match.group(1) if match else "dataset"


def _yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_compatibility_sql(
    current: DatasetSchema,
    proposed: DatasetSchema,
    result: AnalysisResult,
    source_relation: str,
) -> str:
    proposed_names = {column.name for column in proposed.columns}
    unmapped = [
        column.name
        for column in current.columns
        if column.name not in proposed_names and column.name not in result.rename_hints
    ]
    header = [
        "-- Generated by DataHub ChangeGuard.",
        "-- Review and test this proposal before deployment.",
    ]
    if unmapped:
        header.extend(
            [
                "-- SQL generation stopped: the following removed fields have no safe mapping:",
                *[f"--   - {name}" for name in unmapped],
                "-- Add explicit rename hints or retain these fields during a deprecation window.",
                "",
            ]
        )
        return "\n".join(header)

    target_relation = f"{_relation_from_urn(current.dataset_urn)}_compat"
    projections = []
    for column in current.columns:
        replacement = result.rename_hints.get(column.name, column.name)
        if replacement == column.name:
            projections.append(f"    {replacement}")
        else:
            projections.append(f"    {replacement} AS {column.name}")

    return "\n".join(
        [
            *header,
            f"CREATE OR REPLACE VIEW {target_relation} AS",
            "SELECT",
            ",\n".join(projections),
            f"FROM {source_relation};",
            "",
        ]
    )


def render_dbt_schema(proposed: DatasetSchema) -> str:
    model_name = _relation_from_urn(proposed.dataset_urn).split(".")[-1]
    lines = [
        "version: 2",
        "",
        "models:",
        f"  - name: {_yaml_scalar(model_name)}",
        "    config:",
        "      contract:",
        "        enforced: true",
        "    columns:",
    ]
    for column in proposed.columns:
        lines.extend(
            [
                f"      - name: {_yaml_scalar(column.name)}",
                f"        data_type: {_yaml_scalar(column.native_type)}",
            ]
        )
        if column.description:
            lines.append(f"        description: {_yaml_scalar(column.description)}")
        if column.nullable is False:
            lines.extend(["        tests:", "          - not_null"])
    return "\n".join(lines) + "\n"


def render_markdown(
    result: AnalysisResult,
    context: DatasetContext,
    artifact_names: dict[str, str],
) -> str:
    owner_text = ", ".join(result.owners) if result.owners else "Unassigned"
    lines = [
        "# ChangeGuard schema review",
        "",
        f"- **Decision:** `{result.decision.value}`",
        f"- **Risk score:** `{result.risk_score}/100`",
        f"- **Dataset:** `{result.dataset_urn}`",
        f"- **Owners:** {owner_text}",
        f"- **Cataloged downstream assets:** `{result.downstream_count}`",
        f"- **Evidence source:** `{result.evidence_source}`",
        "",
        "## Findings",
        "",
        "| Severity | Code | Field | Finding |",
        "|---|---|---|---|",
    ]
    if result.findings:
        for finding in result.findings:
            escaped_summary = finding.summary.replace("|", "\\|")
            lines.append(
                f"| {finding.severity.value.upper()} | `{finding.code}` | `{finding.field}` | "
                f"{escaped_summary} |"
            )
    else:
        lines.append("| INFO | `NO_BREAKING_CHANGE` | - | No risky schema changes were detected. |")

    lines.extend(["", "## Evidence and remediation", ""])
    for index, finding in enumerate(result.findings, start=1):
        lines.extend(
            [
                f"### {index}. {finding.code}: `{finding.field}`",
                "",
                f"- Severity: **{finding.severity.value.upper()}**",
                f"- Evidence: {finding.evidence}",
                f"- Remediation: {finding.remediation}",
                "- Affected assets: "
                + (", ".join(f"`{urn}`" for urn in finding.affected_assets) or "None cataloged"),
                "",
            ]
        )

    lines.extend(
        [
            "## Generated proposals",
            "",
            f"- Compatibility SQL: `{artifact_names['sql']}`",
            f"- dbt contract: `{artifact_names['dbt']}`",
            f"- Machine-readable audit: `{artifact_names['audit']}`",
            "",
            "## Decision boundary",
            "",
            "ChangeGuard does not deploy generated code. A human or CI policy must review the evidence, "
            "run consumer tests, and approve the release. DataHub writeback is an explicit, separately "
            "confirmed action.",
            "",
        ]
    )
    return "\n".join(lines)


def _severity_badge(severity: Severity) -> str:
    return f'<span class="badge {severity.value}">{severity.value.upper()}</span>'


def _urn_display_name(value: str) -> str:
    return value.rsplit(":", 1)[-1].split("@", 1)[0]


def render_html(result: AnalysisResult, context: DatasetContext) -> str:
    finding_rows = []
    for finding in result.findings:
        assets = (
            "<br>".join(
                f"<span title='{html.escape(urn, quote=True)}'>"
                f"{html.escape(_relation_from_urn(urn))}</span>"
                for urn in finding.affected_assets
            )
            or "None cataloged"
        )
        finding_rows.append(
            "<tr>"
            f"<td data-label='Severity'><div>{_severity_badge(finding.severity)}</div></td>"
            f"<td data-label='Code'><div><code>{html.escape(finding.code)}</code></div></td>"
            f"<td data-label='Field'><div><code>{html.escape(finding.field)}</code></div></td>"
            f"<td data-label='Evidence'><div><strong>{html.escape(finding.summary)}</strong>"
            f"<p>{html.escape(finding.evidence)}</p>"
            f"<p class='remediation'>{html.escape(finding.remediation)}</p></div></td>"
            f"<td data-label='Assets' class='assets'><div>{assets}</div></td>"
            "</tr>"
        )
    if not finding_rows:
        finding_rows.append("<tr><td colspan='5'>No risky schema changes were detected.</td></tr>")

    downstream_items = (
        "".join(
            f"<li><span><strong>{html.escape(item.name)}</strong>"
            f"<small class='fields'>Fields: {html.escape(', '.join(item.fields) or 'table-level only')}</small>"
            f"</span><code>{html.escape(item.urn)}</code>"
            f"<small>{item.hops} hop(s)</small></li>"
            for item in context.downstreams
        )
        or "<li>No downstream assets found</li>"
    )
    owner_text = (
        ", ".join(_urn_display_name(owner) for owner in result.owners)
        if result.owners
        else "Unassigned"
    )
    decision_class = result.decision.value.lower()
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="data:,">
  <title>ChangeGuard review - {html.escape(context.dataset_name)}</title>
  <style>
    :root {{ color-scheme: light; --ink:#17202a; --muted:#5f6b76; --line:#d8dee4;
      --paper:#ffffff; --wash:#f4f6f8; --danger:#b42318; --warning:#b54708;
      --green:#067647; --blue:#175cd3; }}
    * {{ box-sizing:border-box; }}
    body {{ margin:0; background:var(--wash); color:var(--ink); font:14px/1.5 Inter,ui-sans-serif,system-ui,sans-serif; letter-spacing:0; }}
    header {{ background:#12171d; color:#fff; border-bottom:4px solid #d92d20; }}
    .wrap {{ width:min(1180px, calc(100% - 32px)); margin:0 auto; }}
    header .wrap {{ padding:28px 0 24px; }}
    .kicker {{ margin:0 0 8px; color:#9fb7d4; font-size:12px; font-weight:700; text-transform:uppercase; }}
    h1 {{ margin:0; font-size:clamp(24px,4vw,38px); line-height:1.15; letter-spacing:0; overflow-wrap:anywhere; }}
    .urn {{ display:block; margin-top:10px; color:#c6d0da; font:12px/1.45 ui-monospace,SFMono-Regular,monospace; overflow-wrap:anywhere; }}
    main {{ padding:24px 0 48px; }}
    .summary {{ display:grid; grid-template-columns:1.3fr repeat(3,minmax(130px,1fr)); border:1px solid var(--line); background:var(--paper); }}
    .metric {{ min-width:0; padding:18px; border-right:1px solid var(--line); }}
    .metric:last-child {{ border-right:0; }}
    .label {{ display:block; color:var(--muted); font-size:11px; font-weight:700; text-transform:uppercase; }}
    .value {{ display:block; margin-top:4px; font-size:22px; font-weight:750; overflow-wrap:anywhere; }}
    .decision.block {{ color:var(--danger); }} .decision.review {{ color:var(--warning); }} .decision.pass {{ color:var(--green); }}
    section {{ margin-top:24px; }}
    h2 {{ margin:0 0 10px; font-size:18px; letter-spacing:0; }}
    .table-wrap {{ overflow:auto; border:1px solid var(--line); background:var(--paper); }}
    table {{ width:100%; min-width:900px; border-collapse:collapse; }}
    th,td {{ padding:12px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }}
    th {{ background:#edf1f5; color:#344054; font-size:11px; text-transform:uppercase; }}
    th:nth-child(1) {{ width:90px; }} th:nth-child(2) {{ width:170px; }}
    th:nth-child(3) {{ width:110px; }} th:nth-child(5) {{ width:190px; }}
    td p {{ margin:6px 0 0; color:var(--muted); }} td p.remediation {{ color:#344054; }}
    code {{ font:12px/1.45 ui-monospace,SFMono-Regular,monospace; overflow-wrap:anywhere; }}
    .badge {{ display:inline-block; padding:2px 7px; border:1px solid currentColor; border-radius:4px; font-size:10px; font-weight:800; }}
    .badge.critical,.badge.high {{ color:var(--danger); background:#fff1f0; }}
    .badge.medium {{ color:var(--warning); background:#fffaeb; }}
    .badge.low {{ color:var(--blue); background:#eff8ff; }}
    .assets {{ max-width:230px; font:11px/1.45 ui-monospace,SFMono-Regular,monospace; overflow-wrap:anywhere; }}
    .assets span {{ white-space:nowrap; }}
    .downstreams {{ margin:0; padding:0; list-style:none; border:1px solid var(--line); background:var(--paper); }}
    .downstreams li {{ display:grid; grid-template-columns:180px 1fr 80px; gap:12px; align-items:start; padding:10px 12px; border-bottom:1px solid var(--line); }}
    .downstreams li:last-child {{ border-bottom:0; }} .downstreams small {{ color:var(--muted); text-align:right; }}
    .downstreams .fields {{ display:block; margin-top:3px; text-align:left; }}
    .note {{ padding:14px 16px; border-left:4px solid var(--blue); background:#eff8ff; color:#344054; }}
    @media (max-width:760px) {{
      .summary {{ grid-template-columns:1fr 1fr; }}
      .metric {{ border-bottom:1px solid var(--line); }}
      .table-wrap {{ overflow:visible; border:0; background:transparent; }}
      table,tbody {{ display:block; width:100%; min-width:0; }}
      thead {{ display:none; }}
      tr {{ display:block; margin-bottom:12px; border:1px solid var(--line); background:var(--paper); }}
      td {{ display:grid; grid-template-columns:76px minmax(0,1fr); gap:10px; width:100%; padding:10px 12px; }}
      td:last-child {{ border-bottom:0; }}
      td::before {{ content:attr(data-label); color:var(--muted); font-size:10px; font-weight:800; text-transform:uppercase; }}
      td > div {{ min-width:0; overflow-wrap:anywhere; }}
      .assets {{ max-width:none; }}
      .assets span {{ white-space:normal; }}
      .downstreams li {{ grid-template-columns:1fr; }}
      .downstreams small {{ text-align:left; }}
    }}
  </style>
</head>
<body>
  <header><div class="wrap"><p class="kicker">DataHub ChangeGuard</p><h1>Schema change impact review</h1><code class="urn">{html.escape(result.dataset_urn)}</code></div></header>
  <main class="wrap">
    <div class="summary">
      <div class="metric"><span class="label">Decision</span><span class="value decision {decision_class}">{result.decision.value}</span></div>
      <div class="metric"><span class="label">Risk score</span><span class="value">{result.risk_score}/100</span></div>
      <div class="metric"><span class="label">Downstreams</span><span class="value">{result.downstream_count}</span></div>
      <div class="metric"><span class="label">Owner</span><span class="value">{html.escape(owner_text)}</span></div>
    </div>
    <section><h2>Evidence-backed findings</h2><div class="table-wrap"><table><thead><tr><th>Severity</th><th>Code</th><th>Field</th><th>Evidence and action</th><th>Affected assets</th></tr></thead><tbody>{"".join(finding_rows)}</tbody></table></div></section>
    <section><h2>Cataloged downstream graph</h2><ul class="downstreams">{downstream_items}</ul></section>
    <section class="note"><strong>Safety boundary:</strong> generated code is a review proposal. ChangeGuard writes a tag and DATA_SCHEMA incident only when explicit writeback confirmation is supplied.</section>
  </main>
</body>
</html>
"""


def write_artifacts(
    output_dir: str | Path,
    current: DatasetSchema,
    proposed: DatasetSchema,
    context: DatasetContext,
    result: AnalysisResult,
    source_relation: str,
) -> dict[str, Path]:
    target = Path(output_dir)
    target.mkdir(parents=True, exist_ok=True)
    paths = {
        "audit": target / "audit.json",
        "report": target / "report.md",
        "html": target / "report.html",
        "sql": target / "compatibility_view.sql",
        "dbt": target / "dbt_schema.yml",
        "context": target / "datahub_context.json",
    }
    write_json(paths["audit"], result.to_dict())
    write_json(paths["context"], context.to_dict())
    paths["sql"].write_text(
        render_compatibility_sql(current, proposed, result, source_relation), encoding="utf-8"
    )
    paths["dbt"].write_text(render_dbt_schema(proposed), encoding="utf-8")
    names = {key: path.name for key, path in paths.items()}
    paths["report"].write_text(render_markdown(result, context, names), encoding="utf-8")
    paths["html"].write_text(render_html(result, context), encoding="utf-8")
    return paths
