-- Generated by DataHub ChangeGuard.
-- Review and test this proposal before deployment.
CREATE OR REPLACE VIEW commerce.orders_compat AS
SELECT
    order_id,
    customer_id,
    total_amount AS order_total,
    currency,
    created_at
FROM commerce.orders_v2;
